[workspace]

members = [
    "intcode",
    "1/masscalc",
    "2",
    "3",
    "4",
    "6/orbit",
    "7",
    "8",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
]

default-members = ["17"]
